name: Plan for a versioned release
description: Create a to-do list for a versioned release of Rosetta.
title: "[Release]: vX.Y.Z for LANGUAGE"
body:
  - type: textarea
    attributes:
      label: Context
      description: "Please describe the situation that justifies this new version release."
      placeholder: This issue submission describes a roadmap of features to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Checklist
      description: "What new features or changes will be part of this release?"
      placeholder: Each feature should be listed in its own line starting with "- [ ] " followed by a brief description or pull request/issue link.
    validations:
      required: true
