name: Plan for a versioned release
description: Create a to-do list for a versioned release of Rosetta.
title: "[Release]: "
body:
  - type: textarea
    attributes:
      label: Context
      description: "Please describe the situation that justifies this new version release."
      placeholder: This issue submission describes a roadmap of features to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feature Checklist
      description: What did you expect to see when you ran into the issue?
      placeholder: I expected to...
    validations:
      required: true
